### ISSUE TITLE
Error when using `chord.http` in ClojureScript

### ISSUE THREAD

**Issue by colinkahn** [james-henderson/chord#28]
Requiring `chord.http` in my ClojureScript application causes:

```
Caused by: clojure.lang.ExceptionInfo: Referred var fressian-cljs.fns/lookup does not exist at line 1 file:/Users/me/.m2/repository/net/unit8/fressian-cljs/0.1.0/fressian-cljs-0.1.0.jar!/fressian_cljs/reader.cljs
```

This is using version 0.5.0

EDIT: This also happens when I require `chord.client` as well.

**Comment by james-henderson** [comment]
Hi Colin - thanks for the report. This looks like a requiring error upstream in Fressian - that reader.cljs file requires in the `lookup` function but doesn't ever use it, so it should be pretty straightforward to remove it.

Will file a PR with them now.

James

**Comment by james-henderson** [comment]
Hi Colin - I've now moved binary support out to a separate namespace, as of 0.6.0, so this should now work?

**Comment by colinkahn** [comment]
Yup, it's fixed. Thanks!
