### ISSUE TITLE
Error when hitting ws endpoint from cljs

### ISSUE THREAD

**Issue by colinkahn** [james-henderson/chord#30]
I'm getting the same error seen in issues #23 #21 when I hit my `/ws` endpoint from cljs. Here is what my project look likes:

Server:

https://github.com/colinkahn/foo/blob/8a40c80eba76797be7c94b6f4bcaded359fe75e7/src/clj/foo/core.clj

Client:

https://github.com/colinkahn/foo/blob/8a40c80eba76797be7c94b6f4bcaded359fe75e7/src/cljs/foo/core.cljs#L53-L55

Project:

https://github.com/colinkahn/foo/blob/8a40c80eba76797be7c94b6f4bcaded359fe75e7/project.clj

I'm running it using `lein cljsbuild auto dev` in one terminal and `lein ring server` in another.

**Comment by james-henderson** [comment]
Hi Colin - thanks for the report - will take a look.

James

**Comment by james-henderson** [comment]
Hi Colin - I'm afraid Ring's default Jetty adapter doesn't have any support for websockets as yet (that I know of!). Chord currently supports [http-kit](http://www.http-kit.org/), which is a drop-in replacement. 

In the case of your 'foo' project, you can add start/stop functions as follows:

```clojure
(:require [org.httpkit.server :as httpkit])

(defonce !server
  (atom nil))

(defn start-server! []
  (swap! !server
         (fn [running-server]
           (or running-server
               (httpkit/run-server app {:port 8080})))))

(defn stop-server []
  (swap! !server
         (fn [running-server]
           (when running-server
             ;; call the server to stop it
             (running-server)
             nil))))
```

and then call `(start-server!)` from a 'main' function, if required.

James

**Comment by colinkahn** [comment]
@james-henderson thanks, that worked. Can you explain what makes my version require that and the example not? https://github.com/james-henderson/chord/blob/master/example-project/src/chord/example/handler.clj

**Comment by james-henderson** [comment]
Good question, and something that probably isn't particularly clear - the example uses the [Frodo](https://github.com/james-henderson/frodo) plugin, which is essentially the same as lein-ring but sets up an HTTP-kit server instead. We specify `:frodo/config-resource "chord-example.edn"` in the project.clj, then set up the web server handler/port configuration in [chord-example.edn](https://github.com/james-henderson/chord/blob/master/example-project/resources/chord-example.edn).

James

**Comment by colinkahn** [comment]
Very good to know, thanks again!
