### ISSUE TITLE
How do I clean up after a client disconnects?

### ISSUE THREAD

**Issue by magnars** [james-henderson/chord#34]
Thanks for making chord - websockets and core.async is a great match. :-)

One issue: Are there any notifications or callbacks for when a client disconnects? In particular for this websocket endpoint that only sends data, and doesn't receive any. Or do I have to create some manual ACK from the client along with timeouts?

**Comment by magnars** [comment]
@james-henderson A quick question, hope you have time to look at it. :) Thanks!

**Comment by james-henderson** [comment]
Hi Magnars - sorry for not getting back to you sooner. Yes - when a client disconnects, Chord closes the core.async channel - so when you pull a message off the channel, if you find that it's `nil`, the channel's been closed, and you should do any necessary cleanup.

Have gone into more detail in #31, if that helps!

Cheers,

James

**Comment by magnars** [comment]
Aha, so I don't need any ACKs, I can just read off the channel (even if no-one is sending anything to it), and when it closes it will return with `nil`. That makes perfect sense. Thank you!
